name: Build CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Build CLI
      run: dotnet publish CodeBuddy.CLI/CodeBuddy.CLI.csproj -c Release -o publish

    - name: Upload CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: codebuddy-cli
        path: publish/
        if-no-files-found: error
        compression-level: 6