name: Documentation

on:
  push:
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Generate documentation
      run: dotnet run --project CodeBuddy.CLI/CodeBuddy.CLI.csproj -- docs generate --validate --plugins --version
    
    - name: Check documentation quality
      run: |
        dotnet run --project CodeBuddy.CLI/CodeBuddy.CLI.csproj -- docs analyze
        if [ $? -ne 0 ]; then
          echo "Documentation quality check failed"
          exit 1
        fi
      
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/
        if-no-files-found: error
        compression-level: 6
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        keep_files: false